language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dsgDNVyrLabRSnbH5IrYynlqjh7UNchQ4t8KkBaFHM1lG4KnTVz/v77y4W8kjOYVBOUqxcUsZoNHaizqEKs0Qi/v84uGdxqj13LRcUaTF4aW21kzKjygjeYSV5Rpfeo9zZmAnkEAP1+QI1+Y3D9t1UfOPfGyRPJet/lxdBS+EUj811cEM1pUkHbffjOUXQoFIzl6UQRiCHqjkiUVxbH5LwvWlRFmkuW8aFS3gHad9q4PfqlCuoxDSnl3eZMNQGaTrlu13o3enR9OS2w1MzlTrCfhqizP1WAMlU4r8qwg9rMYoPpufBucZW3Z4GpSgt7kaXe0wLXKGfzlom8PsAlXmSrwmacPAZlzfoQjAG658btiQSxn0d/6Q3si5OyZ1arSeg+ci5n2K26jUG6gFE+Qn44KYUWjtJFtCbfZQm26hokN1umuL7EM+pEVUJWPP67gNPHvySKfeRpA6i5zluyWyiPxM1n8BKiNby9YxCjKYWJo8yfKcVeuMlkyygHLftQiENiieS3YPd1ABAFAAT9gx4kehqbn5CmpZUSvCDxpxao2CVCTRkaVyCU8TQy5QH4G6b+HUK8JjMXrSqiY3mow+FN70qog5YWr7+6TE782oX3mBqCwNtvRkuL1EDQMMLjcZbtqKBzRsomRSrL89HDBlzJ6c8dfkACVgxdJ70iaSOs=
  file:
    - "svg-tag-names.js"
    - "svg-tag-names.min.js"
  on:
    tags: true
